-- MySQL Script generated by MySQL Workbench
-- Tue Dec 18 18:41:46 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema forum
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema forum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `forum` DEFAULT CHARACTER SET utf8 ;
USE `forum` ;

-- -----------------------------------------------------
-- Table `forum`.`announce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum`.`announce` (
  `oId` INT(11) NOT NULL AUTO_INCREMENT,
  `announceContent` MEDIUMTEXT NULL DEFAULT NULL COMMENT '公告内容',
  `createTime` DATETIME NOT NULL,
  `status` INT(11) NOT NULL,
  `targetType` INT(11) NOT NULL COMMENT '公告对象类型',
  PRIMARY KEY (`oId`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `forum`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum`.`user` (
  `oId` INT(11) NOT NULL AUTO_INCREMENT,
  `userNickname` VARCHAR(20) NOT NULL COMMENT '用户昵称',
  `userPassword` VARCHAR(32) NOT NULL COMMENT 'md5值加密的密码',
  `userSalt` VARCHAR(16) NOT NULL COMMENT 'MD5加盐的盐',
  `userEmail` VARCHAR(255) NOT NULL COMMENT '用户注册/登录邮箱',
  `userRole` INT(11) NOT NULL COMMENT '用户（权限）角色',
  `userStatus` INT(11) NOT NULL,
  `userProfilePhoto` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`oId`),
  UNIQUE INDEX `userEmail_UNIQUE` (`userEmail` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `forum`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum`.`article` (
  `oId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '代理主键',
  `articleTitle` VARCHAR(255) NOT NULL COMMENT '帖子标题',
  `articleAuthorId` INT(11) NOT NULL COMMENT '发帖者id',
  `articleContent` MEDIUMTEXT NULL DEFAULT NULL COMMENT '帖子正文内容',
  `articleReplyCount` INT(11) NULL DEFAULT NULL COMMENT '回帖数',
  `articleLikeCount` INT(11) NULL DEFAULT NULL COMMENT '点赞数',
  `articleViewCount` INT(11) NULL DEFAULT NULL COMMENT '浏览数',
  `articleTopicId` INT(11) NOT NULL COMMENT '主题区id',
  `articleStatus` INT(11) NULL DEFAULT NULL COMMENT '状态码',
  `createTime` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `latestUpdateTime` DATETIME NULL DEFAULT NULL COMMENT '最后修改时间',
  PRIMARY KEY (`oId`),
  UNIQUE INDEX `oId_UNIQUE` (`oId` ASC),
  INDEX `articleAuthorId_idx` (`articleAuthorId` ASC),
  CONSTRAINT `articleAuthorId`
    FOREIGN KEY (`articleAuthorId`)
    REFERENCES `forum`.`user` (`oId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 103
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `forum`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum`.`comment` (
  `oId` INT(11) NOT NULL AUTO_INCREMENT,
  `userId` INT(11) NOT NULL,
  `entityId` INT(11) NOT NULL,
  `entityType` INT(11) NOT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `status` INT(11) NOT NULL,
  `createTime` DATETIME NOT NULL,
  `likeCount` INT(11) NOT NULL,
  `commentReplyCount` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`oId`),
  INDEX `entity_index` (`entityId` ASC, `entityType` ASC)  COMMENT '查找评论的实体',
  INDEX `user_index` (`userId` ASC)  COMMENT '查找发评论的用户',
  CONSTRAINT `entity_comment_f`
    FOREIGN KEY (`entityId`)
    REFERENCES `forum`.`article` (`oId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `userId_comment_f`
    FOREIGN KEY (`userId`)
    REFERENCES `forum`.`user` (`oId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `forum`.`login_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum`.`login_ticket` (
  `oId` INT(11) NOT NULL AUTO_INCREMENT,
  `userId` INT(11) NOT NULL,
  `ticket` VARCHAR(45) NOT NULL COMMENT '分发到用户cookie的标识token',
  `expired` DATETIME NOT NULL COMMENT 'token过期时间',
  `status` INT(11) NOT NULL,
  PRIMARY KEY (`oId`),
  INDEX `userId_login_ticket_f_idx` (`userId` ASC),
  CONSTRAINT `userId_login_ticket_f`
    FOREIGN KEY (`userId`)
    REFERENCES `forum`.`user` (`oId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `forum`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum`.`session` (
  `oId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '代理主键',
  `userId1` INT(11) NOT NULL,
  `userId2` INT(11) NOT NULL,
  PRIMARY KEY (`oId`),
  UNIQUE INDEX `oId_UNIQUE` (`oId` ASC),
  INDEX `userId1_idx` (`userId1` ASC),
  INDEX `userId2_idx` (`userId2` ASC),
  CONSTRAINT `userId1_session`
    FOREIGN KEY (`userId1`)
    REFERENCES `forum`.`user` (`oId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `userId2_session`
    FOREIGN KEY (`userId2`)
    REFERENCES `forum`.`user` (`oId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 210
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `forum`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum`.`message` (
  `oId` INT(11) NOT NULL AUTO_INCREMENT,
  `senderId` INT(11) NOT NULL COMMENT '私信发送者id',
  `messageContent` TEXT NULL DEFAULT NULL,
  `createTime` DATETIME NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  `receiverId` INT(11) NOT NULL COMMENT '接收者id（保险起见保存的，实际上并不会用到这个字段）',
  `sessionId` INT(11) NOT NULL,
  PRIMARY KEY (`oId`),
  UNIQUE INDEX `oId_UNIQUE` (`oId` ASC),
  INDEX `senderId_idx` (`senderId` ASC),
  INDEX `recepterIdd_idx` (`receiverId` ASC),
  INDEX `sessionId_idx` (`sessionId` ASC),
  CONSTRAINT `recepterId`
    FOREIGN KEY (`receiverId`)
    REFERENCES `forum`.`user` (`oId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `senderId`
    FOREIGN KEY (`senderId`)
    REFERENCES `forum`.`user` (`oId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sessionId_message`
    FOREIGN KEY (`sessionId`)
    REFERENCES `forum`.`session` (`oId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `forum`.`reminder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum`.`reminder` (
  `oId` INT(11) NOT NULL AUTO_INCREMENT,
  `senderId` INT(11) NOT NULL COMMENT '提醒触发者/发送者id',
  `targetId` INT(11) NOT NULL COMMENT '触发动作对象id',
  `targetType` INT(11) NOT NULL COMMENT '触发动作对象类型（主帖/回帖/评论）',
  `action` INT(11) NOT NULL COMMENT '评论/点赞/新回帖',
  `createTime` DATETIME NOT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`oId`),
  UNIQUE INDEX `oId_UNIQUE` (`oId` ASC),
  INDEX `senderId_idx` (`senderId` ASC),
  CONSTRAINT `senderIdf`
    FOREIGN KEY (`senderId`)
    REFERENCES `forum`.`user` (`oId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 96
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `forum`.`reply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum`.`reply` (
  `oId` INT(11) NOT NULL AUTO_INCREMENT,
  `userId` INT(11) NOT NULL COMMENT '被回的主帖oId',
  `targetId` INT(11) NOT NULL COMMENT '该回帖处于的楼层',
  `replyContent` MEDIUMTEXT NULL DEFAULT NULL,
  `likeCount` INT(11) NULL DEFAULT NULL,
  `commentId` INT(11) NOT NULL,
  `createTime` DATETIME NOT NULL,
  `status` INT(11) NOT NULL,
  PRIMARY KEY (`oId`),
  UNIQUE INDEX `oId_UNIQUE` (`oId` ASC),
  INDEX `replyToId_f_idx` (`userId` ASC),
  INDEX `commentId_reply_f_idx` (`commentId` ASC),
  INDEX `targetId_reply_f_idx` (`targetId` ASC),
  CONSTRAINT `commentId_reply_f`
    FOREIGN KEY (`commentId`)
    REFERENCES `forum`.`comment` (`oId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `targetId_reply_f`
    FOREIGN KEY (`targetId`)
    REFERENCES `forum`.`user` (`oId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `userId_reply_f`
    FOREIGN KEY (`userId`)
    REFERENCES `forum`.`user` (`oId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `forum`.`user_like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum`.`user_like` (
  `oId` INT(11) NOT NULL AUTO_INCREMENT,
  `userId` INT(11) NOT NULL,
  `entityId` INT(11) NOT NULL COMMENT '用户点赞对象id',
  `entityType` INT(11) NOT NULL COMMENT '用户点赞对象类型',
  `createTime` DATETIME NOT NULL,
  `status` INT(11) NOT NULL,
  PRIMARY KEY (`oId`),
  UNIQUE INDEX `oId_UNIQUE` (`oId` ASC),
  INDEX `userId_f_idx` (`userId` ASC),
  INDEX `userId_f_onlike_idx` (`userId` ASC),
  CONSTRAINT `userId_user_like_f`
    FOREIGN KEY (`userId`)
    REFERENCES `forum`.`user` (`oId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `forum`.`user_notify`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum`.`user_notify` (
  `oId` INT(11) NOT NULL AUTO_INCREMENT,
  `userId` INT(11) NOT NULL COMMENT '消息接收者id',
  `createTime` DATETIME NOT NULL COMMENT '用于排序筛选的消息创建时间（与Notify系列表中的createTime字段一致）',
  `hasRead` INT(11) NOT NULL COMMENT '该消息是否已读',
  `notifyId` INT(11) NOT NULL COMMENT '消息内容id',
  `notifyType` INT(11) NOT NULL COMMENT '消息类型',
  PRIMARY KEY (`oId`),
  UNIQUE INDEX `oId_UNIQUE` (`oId` ASC),
  INDEX `userId_f_onnotify_idx` (`userId` ASC),
  CONSTRAINT `userId_f_onnotify`
    FOREIGN KEY (`userId`)
    REFERENCES `forum`.`user` (`oId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `forum`.`user_subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum`.`user_subscription` (
  `oId` INT(11) NOT NULL AUTO_INCREMENT,
  `userId` INT(11) NOT NULL,
  `targetType` INT(11) NOT NULL COMMENT '订阅规则的动作对象类型',
  `action` INT(11) NOT NULL COMMENT '订阅规则的动作类型',
  `createTime` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`oId`),
  UNIQUE INDEX `oId_UNIQUE` (`oId` ASC),
  INDEX `userId_f_onsubscription_idx` (`userId` ASC),
  CONSTRAINT `userId_f_onsubscription`
    FOREIGN KEY (`userId`)
    REFERENCES `forum`.`user` (`oId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 166
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
